import { Trade } from '@/types'

export const TRADE_DEFAULTS: Record<string, { markup: number; waste: number; labor: number }> = {
  foundation: { markup: 40, waste: 15, labor: 90 },
  roofing: { markup: 35, waste: 12, labor: 85 },
  remodel: { markup: 38, waste: 10, labor: 82 },
  kitchen: { markup: 45, waste: 12, labor: 88 },
  concrete: { markup: 42, waste: 8, labor: 80 },
  framing: { markup: 36, waste: 8, labor: 82 },
  windows: { markup: 40, waste: 5, labor: 85 },
  siding: { markup: 38, waste: 10, labor: 82 },
  exterior: { markup: 38, waste: 10, labor: 82 },
  hvac: { markup: 40, waste: 8, labor: 90 },
  plumbing: { markup: 40, waste: 8, labor: 95 },
  electrical: { markup: 40, waste: 5, labor: 100 },
}

export const TAX_RATES: Record<string, number> = {
  MA: 0.0625,
  RI: 0.07,
  CT: 0.0635,
  NH: 0,
}

export const REGIONS = {
  MA: [
    'Boston, MA',
    'Worcester, MA',
    'Springfield, MA',
    'Cambridge, MA',
    'Lowell, MA',
    'Brockton, MA',
    'Quincy, MA',
    'Lynn, MA',
  ],
  RI: [
    'Providence, RI',
    'Cranston, RI',
    'Warwick, RI',
    'Pawtucket, RI',
  ],
  CT: [
    'Hartford, CT',
    'New Haven, CT',
    'Stamford, CT',
    'Bridgeport, CT',
  ],
  NH: [
    'Manchester, NH',
    'Nashua, NH',
    'Concord, NH',
    'Dover, NH',
  ],
}

export const TRADE_COLORS: Record<string, string> = {
  foundation: 'bg-amber-900/40 text-amber-400 border-amber-800/50',
  roofing: 'bg-blue-900/40 text-blue-400 border-blue-800/50',
  remodel: 'bg-purple-900/40 text-purple-400 border-purple-800/50',
  kitchen: 'bg-orange-900/40 text-orange-400 border-orange-800/50',
  concrete: 'bg-gray-800/60 text-gray-300 border-gray-700/50',
  framing: 'bg-yellow-900/40 text-yellow-400 border-yellow-800/50',
  windows: 'bg-cyan-900/40 text-cyan-400 border-cyan-800/50',
  siding: 'bg-teal-900/40 text-teal-400 border-teal-800/50',
  exterior: 'bg-green-900/40 text-green-400 border-green-800/50',
  hvac: 'bg-red-900/40 text-red-400 border-red-800/50',
  plumbing: 'bg-blue-900/40 text-blue-300 border-blue-800/50',
  electrical: 'bg-yellow-900/40 text-yellow-300 border-yellow-800/50',
}

export const STATUS_STYLES: Record<string, string> = {
  lead: 'bg-panel text-text-secondary border-border',
  scheduled: 'bg-blue-900/30 text-blue-400 border-blue-800/40',
  inspected: 'bg-purple-900/30 text-purple-400 border-purple-800/40',
  quoted: 'bg-amber-900/30 text-amber-400 border-amber-800/40',
  sold: 'bg-gold-dim/30 text-gold-light border-gold-dim/40',
  in_progress: 'bg-green-900/30 text-green-DEFAULT border-green-dim/40',
  complete: 'bg-green-900/50 text-green-DEFAULT border-green-dim/60',
  cancelled: 'bg-red-900/30 text-red-400 border-red-800/40',
  draft: 'bg-panel text-text-secondary border-border',
  sent: 'bg-blue-900/30 text-blue-400 border-blue-800/40',
  awaiting_signature: 'bg-amber-900/30 text-amber-400 border-amber-800/40',
  signed: 'bg-green-900/40 text-green-DEFAULT border-green-dim/50',
  declined: 'bg-red-900/30 text-red-400 border-red-800/40',
  available: 'text-green-DEFAULT',
  busy: 'text-amber-DEFAULT',
  unavailable: 'text-text-muted',
}

export const PIPELINE_STAGES = [
  { key: 'lead', label: 'Lead', color: '#606070' },
  { key: 'scheduled', label: 'Scheduled', color: '#4a9de0' },
  { key: 'inspected', label: 'Inspected', color: '#9b6dd4' },
  { key: 'quoted', label: 'Quoted', color: '#d4880a' },
  { key: 'sold', label: 'Sold', color: '#c8922a' },
  { key: 'in_progress', label: 'In Progress', color: '#3eb85a' },
]

export const MOCK_JOBS = [
  {
    id: '1',
    job_number: 'JOB-0001',
    customer: { name: 'Rivera Residence', address: '142 Maple St', city: 'Boston', state: 'MA' },
    trade: 'roofing',
    status: 'in_progress',
    subcontractor: { company: 'Peak Roofing LLC' },
    quoted_value: 18500,
    matterport_url: 'https://matterport.com/models/abc123',
    onedrive_url: 'https://onedrive.com/xyz',
    rilla_url: 'https://rilla.com/call/001',
    rilla_score: 84,
    audit_complete: false,
  },
  {
    id: '2',
    job_number: 'JOB-0002',
    customer: { name: 'Walsh Commercial', address: '890 Industrial Ave', city: 'Worcester', state: 'MA' },
    trade: 'foundation',
    status: 'quoted',
    subcontractor: { company: 'Deep Dig Foundation' },
    quoted_value: 42000,
    matterport_url: '',
    onedrive_url: 'https://onedrive.com/abc',
    rilla_url: '',
    rilla_score: 71,
    audit_complete: false,
  },
  {
    id: '3',
    job_number: 'JOB-0003',
    customer: { name: 'Chen Remodel', address: '55 Oak Ave', city: 'Providence', state: 'RI' },
    trade: 'kitchen',
    status: 'sold',
    subcontractor: { company: 'Premier Interiors' },
    quoted_value: 29800,
    matterport_url: 'https://matterport.com/models/def456',
    onedrive_url: '',
    rilla_url: 'https://rilla.com/call/003',
    rilla_score: 91,
    audit_complete: true,
  },
  {
    id: '4',
    job_number: 'JOB-0004',
    customer: { name: 'Kowalski Home', address: '3 Birch Rd', city: 'Manchester', state: 'NH' },
    trade: 'siding',
    status: 'inspected',
    subcontractor: null,
    quoted_value: null,
    matterport_url: 'https://matterport.com/models/ghi789',
    onedrive_url: 'https://onedrive.com/def',
    rilla_url: 'https://rilla.com/call/004',
    rilla_score: 62,
    audit_complete: false,
  },
  {
    id: '5',
    job_number: 'JOB-0005',
    customer: { name: 'Patel Properties', address: '77 Commerce Blvd', city: 'Hartford', state: 'CT' },
    trade: 'concrete',
    status: 'scheduled',
    subcontractor: { company: 'SolidForm Concrete' },
    quoted_value: 11200,
    matterport_url: '',
    onedrive_url: '',
    rilla_url: '',
    rilla_score: null,
    audit_complete: false,
  },
  {
    id: '6',
    job_number: 'JOB-0006',
    customer: { name: 'Torres Framing', address: '200 Mill St', city: 'Lowell', state: 'MA' },
    trade: 'framing',
    status: 'lead',
    subcontractor: null,
    quoted_value: null,
    matterport_url: '',
    onedrive_url: '',
    rilla_url: '',
    rilla_score: null,
    audit_complete: false,
  },
]

export const MOCK_SUBS = [
  { id: '1', company: 'Peak Roofing LLC', contact_name: 'Dave Kowalski', trade: 'roofing', crew_size: 6, status: 'available', license_number: 'MA-ROF-20891', license_expiry: '2025-11-30', hourly_rate: 85, phone: '617-555-0142', email: 'dave@peakroofing.com', city: 'Boston', state: 'MA' },
  { id: '2', company: 'Deep Dig Foundation', contact_name: 'Maria Santos', trade: 'foundation', crew_size: 4, status: 'busy', license_number: 'MA-FND-14422', license_expiry: '2025-06-15', hourly_rate: 90, phone: '508-555-0288', email: 'maria@deepdig.com', city: 'Worcester', state: 'MA' },
  { id: '3', company: 'Premier Interiors', contact_name: 'Tom Ricci', trade: 'remodel', crew_size: 5, status: 'available', license_number: 'RI-REM-88211', license_expiry: '2026-02-28', hourly_rate: 82, phone: '401-555-0199', email: 'tom@premierinteriors.com', city: 'Providence', state: 'RI' },
  { id: '4', company: 'SolidForm Concrete', contact_name: 'James Park', trade: 'concrete', crew_size: 3, status: 'available', license_number: 'CT-CON-55901', license_expiry: '2025-09-01', hourly_rate: 80, phone: '860-555-0377', email: 'james@solidform.com', city: 'Hartford', state: 'CT' },
  { id: '5', company: 'New England Frame Co.', contact_name: 'Sarah Mitchell', trade: 'framing', crew_size: 7, status: 'unavailable', license_number: 'NH-FRM-30140', license_expiry: '2026-04-30', hourly_rate: 82, phone: '603-555-0416', email: 'sarah@neframeco.com', city: 'Manchester', state: 'NH' },
  { id: '6', company: 'ClearView Windows', contact_name: 'Carlos Diaz', trade: 'windows', crew_size: 2, status: 'busy', license_number: 'MA-WIN-67234', license_expiry: '2025-08-15', hourly_rate: 85, phone: '617-555-0533', email: 'carlos@clearviewwin.com', city: 'Quincy', state: 'MA' },
]

export const MOCK_CUSTOMERS = [
  { id: '1', name: 'Rivera Residence', address: '142 Maple St', city: 'Boston', state: 'MA', zip: '02101', phone: '617-555-0091', email: 'jrivera@email.com', jobs_count: 2, lifetime_value: 32500, last_contact: '2026-04-15', status: 'active' },
  { id: '2', name: 'Walsh Commercial', address: '890 Industrial Ave', city: 'Worcester', state: 'MA', zip: '01601', phone: '508-555-0142', email: 'bwalsh@walshco.com', jobs_count: 1, lifetime_value: 42000, last_contact: '2026-04-10', status: 'active' },
  { id: '3', name: 'Chen Remodel', address: '55 Oak Ave', city: 'Providence', state: 'RI', zip: '02903', phone: '401-555-0288', email: 'lchen@email.com', jobs_count: 3, lifetime_value: 68400, last_contact: '2026-04-18', status: 'active' },
  { id: '4', name: 'Kowalski Home', address: '3 Birch Rd', city: 'Manchester', state: 'NH', zip: '03101', phone: '603-555-0333', email: 'mkowalski@email.com', jobs_count: 1, lifetime_value: 9800, last_contact: '2026-03-28', status: 'prospect' },
  { id: '5', name: 'Patel Properties', address: '77 Commerce Blvd', city: 'Hartford', state: 'CT', zip: '06103', phone: '860-555-0455', email: 'rpatel@patelprops.com', jobs_count: 4, lifetime_value: 87200, last_contact: '2026-04-12', status: 'active' },
]
